### ISSUE TITLE
report Synchronized = False

### ISSUE THREAD

**Issue by maowenniao** [ThomasDavidDev/PPMdecode#1]
Dear, When I run this project in my Arduino, it report "Synchronized = False" in the Serial monitor.
How to solve it?

**Comment by ThomasDevoogdt** [comment]
Additional information will be required to solve your problem.  I have not been working on this library for a while.  But I can try to help you.

* First, its important to make sure the correct pin is used for the interrupt.  (pin 2 on an Arduino Uno)
 * Add some logging in the library code.  Something like ```Serial.print("Interrupt triggered");```. Note that this is purely for debugging, interrupts should not log something.
* Print the time between the interrupts. You should see a repetitive PPM signal. If this is not the case, then there's possibly something wrong with your setup. 

Succes with Debugging! 

I will close this issue because there's no direct link to a bug in *this* library.  But you can comment further on this thread.
